/* File: f_tilecyclesmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Mon Apr  5 02:06:34 2021
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *f_tilecycles_error;
static PyObject *f_tilecycles_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj, 0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = f_tilecycles_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_WRAPPEDFUNC_US(find_cycle,FIND_CYCLE)(int*,int*,int*,int*,int*,int*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************* find_cycle *********************************/
static char doc_f2py_rout_f_tilecycles_find_cycle[] = "\
find_cycle(neis,Nneis,chain,Nchain,cycle,Ncycle)\n\nWrapper for ``find_cycle``.\
\n\nParameters\n----------\n"
"neis : input rank-2 array('i') with bounds (4,(Nnodes))\n"
"Nneis : input rank-1 array('i') with bounds ((Nnodes))\n"
"chain : input rank-1 array('i') with bounds (f2py_chain_d0)\n"
"Nchain : input int\n"
"cycle : input rank-1 array('i') with bounds (f2py_cycle_d0)\n"
"Ncycle : input int";
/* extern void F_WRAPPEDFUNC_US(find_cycle,FIND_CYCLE)(int*,int*,int*,int*,int*,int*,int*,int*); */
static PyObject *f2py_rout_f_tilecycles_find_cycle(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  int *neis = NULL;
  npy_intp neis_Dims[2] = {-1, -1};
  const int neis_Rank = 2;
  PyArrayObject *capi_neis_tmp = NULL;
  int capi_neis_intent = 0;
  PyObject *neis_capi = Py_None;
  int *Nneis = NULL;
  npy_intp Nneis_Dims[1] = {-1};
  const int Nneis_Rank = 1;
  PyArrayObject *capi_Nneis_tmp = NULL;
  int capi_Nneis_intent = 0;
  PyObject *Nneis_capi = Py_None;
  int *chain = NULL;
  npy_intp chain_Dims[1] = {-1};
  const int chain_Rank = 1;
  PyArrayObject *capi_chain_tmp = NULL;
  int capi_chain_intent = 0;
  PyObject *chain_capi = Py_None;
  int Nchain = 0;
  PyObject *Nchain_capi = Py_None;
  int *cycle = NULL;
  npy_intp cycle_Dims[1] = {-1};
  const int cycle_Rank = 1;
  PyArrayObject *capi_cycle_tmp = NULL;
  int capi_cycle_intent = 0;
  PyObject *cycle_capi = Py_None;
  int Ncycle = 0;
  PyObject *Ncycle_capi = Py_None;
  int f2py_chain_d0 = 0;
  int f2py_cycle_d0 = 0;
    static char *capi_kwlist[] = {"neis","Nneis","chain","Nchain","cycle","Ncycle",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOO|:f_tilecycles.find_cycle",\
        capi_kwlist,&neis_capi,&Nneis_capi,&chain_capi,&Nchain_capi,&cycle_capi,&Ncycle_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable neis */
  neis_Dims[0]=4,neis_Dims[1]=(Nnodes);
  capi_neis_intent |= F2PY_INTENT_IN;
  capi_neis_tmp = array_from_pyobj(NPY_INT,neis_Dims,neis_Rank,capi_neis_intent,neis_capi);
  if (capi_neis_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : f_tilecycles_error,"failed in converting 1st argument `neis' of f_tilecycles.find_cycle to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    neis = (int *)(PyArray_DATA(capi_neis_tmp));

  /* Processing variable Nneis */
  Nneis_Dims[0]=(Nnodes);
  capi_Nneis_intent |= F2PY_INTENT_IN;
  capi_Nneis_tmp = array_from_pyobj(NPY_INT,Nneis_Dims,Nneis_Rank,capi_Nneis_intent,Nneis_capi);
  if (capi_Nneis_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : f_tilecycles_error,"failed in converting 2nd argument `Nneis' of f_tilecycles.find_cycle to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    Nneis = (int *)(PyArray_DATA(capi_Nneis_tmp));

  /* Processing variable chain */
  ;
  capi_chain_intent |= F2PY_INTENT_IN;
  capi_chain_tmp = array_from_pyobj(NPY_INT,chain_Dims,chain_Rank,capi_chain_intent,chain_capi);
  if (capi_chain_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : f_tilecycles_error,"failed in converting 3rd argument `chain' of f_tilecycles.find_cycle to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    chain = (int *)(PyArray_DATA(capi_chain_tmp));

  /* Processing variable cycle */
  ;
  capi_cycle_intent |= F2PY_INTENT_IN;
  capi_cycle_tmp = array_from_pyobj(NPY_INT,cycle_Dims,cycle_Rank,capi_cycle_intent,cycle_capi);
  if (capi_cycle_tmp == NULL) {
    PyObject *exc, *val, *tb;
    PyErr_Fetch(&exc, &val, &tb);
    PyErr_SetString(exc ? exc : f_tilecycles_error,"failed in converting 5th argument `cycle' of f_tilecycles.find_cycle to C/Fortran array" );
    npy_PyErr_ChainExceptionsCause(exc, val, tb);
  } else {
    cycle = (int *)(PyArray_DATA(capi_cycle_tmp));

  /* Processing variable Ncycle */
    f2py_success = int_from_pyobj(&Ncycle,Ncycle_capi,"f_tilecycles.find_cycle() 6th argument (Ncycle) can't be converted to int");
  if (f2py_success) {
  /* Processing variable Nchain */
    f2py_success = int_from_pyobj(&Nchain,Nchain_capi,"f_tilecycles.find_cycle() 4th argument (Nchain) can't be converted to int");
  if (f2py_success) {
  /* Processing variable f2py_chain_d0 */
  f2py_chain_d0 = shape(chain, 0);
  /* Processing variable f2py_cycle_d0 */
  f2py_cycle_d0 = shape(cycle, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(neis,Nneis,chain,&Nchain,cycle,&Ncycle,&f2py_chain_d0,&f2py_cycle_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_cycle_d0 */
  /* End of cleaning variable f2py_chain_d0 */
  } /*if (f2py_success) of Nchain*/
  /* End of cleaning variable Nchain */
  } /*if (f2py_success) of Ncycle*/
  /* End of cleaning variable Ncycle */
  if((PyObject *)capi_cycle_tmp!=cycle_capi) {
    Py_XDECREF(capi_cycle_tmp); }
  }  /*if (capi_cycle_tmp == NULL) ... else of cycle*/
  /* End of cleaning variable cycle */
  if((PyObject *)capi_chain_tmp!=chain_capi) {
    Py_XDECREF(capi_chain_tmp); }
  }  /*if (capi_chain_tmp == NULL) ... else of chain*/
  /* End of cleaning variable chain */
  if((PyObject *)capi_Nneis_tmp!=Nneis_capi) {
    Py_XDECREF(capi_Nneis_tmp); }
  }  /*if (capi_Nneis_tmp == NULL) ... else of Nneis*/
  /* End of cleaning variable Nneis */
  if((PyObject *)capi_neis_tmp!=neis_capi) {
    Py_XDECREF(capi_neis_tmp); }
  }  /*if (capi_neis_tmp == NULL) ... else of neis*/
  /* End of cleaning variable neis */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of find_cycle *****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"find_cycle",-1,{{-1}},0,(char *)F_WRAPPEDFUNC_US(find_cycle,FIND_CYCLE),(f2py_init_func)f2py_rout_f_tilecycles_find_cycle,doc_f2py_rout_f_tilecycles_find_cycle},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "f_tilecycles",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};

PyMODINIT_FUNC PyInit_f_tilecycles(void) {
  int i;
  PyObject *m,*d, *s, *tmp;
  m = f_tilecycles_module = PyModule_Create(&moduledef);
  Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module f_tilecycles (failed to import numpy)"); return m;}
  d = PyModule_GetDict(m);
  s = PyUnicode_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  Py_DECREF(s);
  s = PyUnicode_FromString(
    "This module 'f_tilecycles' is auto-generated with f2py (version:2).\nFunctions:\n"
"  find_cycle(neis,Nneis,chain,Nchain,cycle,Ncycle)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  Py_DECREF(s);
  s = PyUnicode_FromString("1.20.1");
  PyDict_SetItemString(d, "__f2py_numpy_version__", s);
  Py_DECREF(s);
  f_tilecycles_error = PyErr_NewException ("f_tilecycles.error", NULL, NULL);
  /*
   * Store the error object inside the dict, so that it could get deallocated.
   * (in practice, this is a module, so it likely will not and cannot.)
   */
  PyDict_SetItemString(d, "_f_tilecycles_error", f_tilecycles_error);
  Py_DECREF(f_tilecycles_error);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }

    {
      extern void F_FUNC_US(find_cycle,FIND_CYCLE)(void);
      PyObject* o = PyDict_GetItemString(d,"find_cycle");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC_US(find_cycle,FIND_CYCLE),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("find_cycle");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }
    
/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"f_tilecycles");
#endif
  return m;
}
#ifdef __cplusplus
}
#endif
