!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrapfind_cycle (neis, Nneis, chain, Nchain, cycle, &
     &Ncycle, f2py_chain_d0, f2py_cycle_d0)
      integer Nchain
      integer Ncycle
      integer f2py_chain_d0
      integer f2py_cycle_d0
      integer neis(4,(Nnodes))
      integer Nneis((Nnodes))
      integer chain(f2py_chain_d0)
      integer cycle(f2py_cycle_d0)
      interface
      
            subroutine find_cycle(neis,Nneis,chain,Nchain,cycle,Ncycle) 
                integer, intent(IN),dimension(4, Nnodes) :: neis
                integer, intent(IN),dimension(Nnodes) :: Nneis
                integer, intent(INOUT),dimension(:) :: chain
                integer, intent(INOUT) :: Nchain
                integer, intent(OUT),dimension(:) :: cycle
                integer, intent(OUT) :: Ncycle
            end subroutine find_cycle
      end interface
      call find_cycle(neis, Nneis, chain, Nchain, cycle, Ncycle)
      end

